locals {
  region_codes = {
    "eastus"             = "use1"
    "eastus2"            = "use2"
    "centralus"          = "usc1"
    "westus"             = "usw1"
    "westus2"            = "usw2"
    "westus3"            = "usw3"
    "northcentralus"     = "usn1"
    "southcentralus"     = "uss1"
    "westcentralus"      = "uswc"
    "canadacentral"      = "cac1"
    "canadaeast"         = "cae1"
    "westeurope"         = "euw1"
    "northeurope"        = "eun1"
    "uksouth"            = "uks1"
    "ukwest"             = "ukw1"
    "francecentral"      = "frc1"
    "germanywestcentral" = "dwc1"
    "switzerlandnorth"   = "chn1"
    "norwayeast"         = "noe1"
    "swedencentral"      = "sec1"
    "eastasia"           = "ase1"
    "southeastasia"      = "asse"
    "japaneast"          = "jpe1"
    "japanwest"          = "jpw1"
    "australiaeast"      = "aue1"
    "australiasoutheast" = "ause"
    "koreacentral"       = "krc1"
    "koreasouth"         = "krs1"
    "centralindia"       = "inc1"
    "southindia"         = "ins1"
    "brazilsouth"        = "brs1"
    "southafricanorth"   = "zan1"
    "uaenorth"           = "aen1"
  }

  region_code = local.region_codes[var.region]
}
